apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - host: config-ui.devlake.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: config-ui
            port: 
              number: 4000

  - host: devlake.devlake.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devlake
            port:
              number: 8080

  - host: grafana.devlake.test
    http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana 
            port: 
              number: 3000
