apiVersion: v1
kind: Secret
metadata:
  name: grafana
type: Opaque
data:
  MYSQL_DATABASE: bGFrZQ==
  MYSQL_USER: bWVyaWNv
  MYSQL_PASSWORD: bWVyaWNv
  GF_SERVER_ROOT_URL: aHR0cDovL2NvbmZpZy11aTo0MDAwL2dyYWZhbmE=
  GF_USERS_DEFAULT_THEME: bGlnaHQ=
  MYSQL_URL: bXlzcWw6MzMwNg==