apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-ui
  labels:
    app: config-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-ui
  template:
    metadata:
      labels:
        app: config-ui
    spec:
      containers:
      - name: config-ui
        image: mericodev/devlake-config-ui:latest
        ports:
        - containerPort: 4000
        envFrom:
          - secretRef:
              name: config-ui